apiVersion: v1
kind: Service
metadata:
  name: traefik-web
  namespace: default
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: web
      port: 80
    - protocol: TCP
      name: admin
      port: 8080
    - protocol: TCP
      name: websecure
      port: 443
    - protocol: TCP
      name: redis
      port: 6379
  selector:
    app: traefik-web
